### ISSUE TITLE
Typfout QC

### ISSUE THREAD

**Issue by MichielVieijra** [vergauwenthomas/vlinder_toolkit#24]
Typfout persistance QC

**Comment by vergauwenthomas** [comment]
You can solve this directly in the master, you do not need to make a seperate branch for this.

**Comment by MichielVieijra** [comment]
Moet ik dan gewoon git add... git commit... git push... in master doen?

**Comment by vergauwenthomas** [comment]
@MichielVieijra  Ja, typo's mag je rechtstreeks in de master doen. Eerst even je locale master updaten (zodat je de meest recente online versie hebt).
`git checkout master`, `git pull`, aanpassingen doen, `git add ...`, `git commit ...`, `git push`
