### ISSUE TITLE
Info about QC

### ISSUE THREAD

**Issue by MichielVieijra** [vergauwenthomas/vlinder_toolkit#37]
Write function to get info about QC results:
1) percentage of each outlier type
2) number of datapoints that are flagged
...

**Comment by vergauwenthomas** [comment]
@MichielVieijra Frequency statistic + pie-charts are included in [104807a](https://github.com/vergauwenthomas/vlinder_toolkit/pull/36/commits/104807a66ef7c87f5423f4dfd1e46ea93195c477)
Only thing left to do is to make a time depending plot. To do this you need:

- [ ] create default colors for each check-outlier in plot settings
- [ ] create a timeseries plot function that can take these colors as input
- [ ] make function to aggregate the frequency satistics per timestamp (and per subset of stations, so add stationnames to the input of this function)
- [ ] put it in the pipline of the 'get_qc_stats'
